### PR TITLE
Visual Studio 2019 build fix.

### PR DESCRIPTION
**Pull request by konard**
Please merge the build fix and republish the NuGet package. This is required to check that the `packagetest` is building.

### CODE REVIEW

**Comment by konard** [comment]
You can also watch the recording of this change here: https://youtu.be/GQRMRXP0o-4

**Comment by robertvazan** [comment]
NuGet package was last published manually in an environment that no longer exists. I will check whether GitHub Actions can be used for this purpose. Any hints?

**Comment by konard** [comment]
Yes it can be used.

**Comment by konard** [comment]
I use these scripts at the moment:
https://github.com/linksplatform/Scripts/blob/master/MultiProjectRepository/read_cpp_package_info.sh
https://github.com/linksplatform/Scripts/blob/master/MultiProjectRepository/push-cpp-nuget.sh

I also have the script for automatic GitHub's release generation:
https://github.com/linksplatform/Scripts/blob/master/MultiProjectRepository/publish-release.sh

**Comment by robertvazan** [comment]
Thanks. These scripts however seem to either assume the C++ build has already completed or that it will be triggered during NuGet packaging. I made NuGet work on Linux before with C# and .NET Core. Any idea what dependencies does it have for C++ builds? Or are these scripts intended to be run via GitHub Actions?

**Comment by konard** [comment]
Your package is source-code package it does not require build. Just .nuspec is enough. I will add the build and test later, to make sure that source code is valid before packaging. These scripts intended to be run via GitHub Actions, specifically under `ubuntu-latest`. And yes they are used after build and test, but in this case packaging can be done directly from the source code.

**Comment by robertvazan** [comment]
Ah. I completely forgot about that. Good. I will publish it. I have to do something else right now, but I will try to get back to this ASAP.

**Comment by konard** [comment]
@robertvazan here is an example of GitHub Actions' workflow for these scripts: https://github.com/linksplatform/Delegates/blob/master/.github/workflows/CD.yml

**Comment by konard** [comment]
@robertvazan any update? If you didn't start to publish the NuGet package, I`ll make it myself and republish it with a different name, so you'll have a tested example.

**Comment by robertvazan** [comment]
Please give me a bit of time. I am very busy. I have this in the list of top priorities. Should be done in a few days at most. Sorry for the wait. Better not to publish two packages as that would be confusing for users.

**Comment by konard** [comment]
Looks like I've finished everything except this task. NuGet does allow to unlist the packages, so I'll do the test package anyway, once you'll upload the main one I'll unlist the test package. This also will help you with publishing, it will require from you just copy and paste the workflow file and the NuGet token into your repository's secrets.

**Comment by konard** [comment]
Oh. Wow, you have published it. I didn`t notice. Thank you.

**Comment by robertvazan** [comment]
Not yet. I am fixing last few issues.

**Comment by konard** [comment]
https://www.nuget.org/packages/Crc32C/1.1.5 this version is ok?

**Comment by robertvazan** [comment]
Yup. That version should work. I now have a release script, so that I can quickly publish new version whenever sources change.

**Comment by konard** [comment]
Ok, I`ll start porting soon. Let's continue there: https://github.com/robertvazan/crc32c-hw/issues/1#issuecomment-597269563

**Pull request merged**
